export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CHANGE_IMAGE_URL = 'CHANGE_IMAGE_URL';
export const REQUEST_FACES_PENDING = 'GET_FACES_PENDING';
export const REQUEST_FACES_SUCCESS = 'GET_FACES_SUCCESS';
export const REQUEST_FACES_FAILED = 'GET_FACES_FAILED';
export const UPDATE_ENTRIES = 'UPDATE_ENTRIES'; 